version: '3.8'

services:
  # mysql------------------------------------------
  mysql:
    image: mysql:8.0
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      # MYSQL_ROOT_PASSWORD: "Dong10052002@"
      # MYSQL_USER: ${USER_NAME}
      MYSQL_ROOT_PASSWORD: $MYSQLDB_PASSWORD
      # MYSQL_DATABASE: ${DB_NAME}
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    env_file:
      - .env
    networks:
      - backend_network

  #Backend
  backend_mobile:
    container_name: backend_mobile
    build: .
    restart: always
    ports:
      - $BACKEND_LOCAL_PORT:$BACKEND_DOCKER_PORT
    environment:
      - DB_HOST=$MYSQLDB_HOST
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_PASSWORD
      - DB_DATABASE=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
    volumes:
      - ./:/app/
      - /app/node_modules
    depends_on:
      - mysql
    networks:
      - backend_network
networks:
  backend_network:
volumes:
  mysql:
